export interface CityData {
  slug: string
  name: string
  state: string
  stateAbbr: string
  population: number
  region: string
  economy: string[]
  context: string
}

export const cities: CityData[] = [
  { slug: 'sao-paulo', name: 'São Paulo', state: 'São Paulo', stateAbbr: 'SP', population: 11451245, region: 'Sudeste', economy: ['finanças', 'tecnologia', 'comércio', 'indústria'], context: 'Com mais de 11 milhões de habitantes, São Paulo é o maior centro financeiro e empresarial da América Latina, concentrando a maior densidade de empresas e consumidores do país.' },
  { slug: 'rio-de-janeiro', name: 'Rio de Janeiro', state: 'Rio de Janeiro', stateAbbr: 'RJ', population: 6211223, region: 'Sudeste', economy: ['turismo', 'petróleo e gás', 'serviços', 'cultura'], context: 'Segundo maior mercado consumidor do Brasil, o Rio de Janeiro combina um polo turístico mundial com um setor de serviços e energia que movimenta bilhões anualmente.' },
  { slug: 'brasilia', name: 'Brasília', state: 'Distrito Federal', stateAbbr: 'DF', population: 2817068, region: 'Centro-Oeste', economy: ['administração pública', 'serviços', 'comércio', 'tecnologia'], context: 'Capital federal e sede dos três poderes, Brasília concentra um grande mercado de serviços especializados e uma população com alto poder aquisitivo médio.' },
  { slug: 'salvador', name: 'Salvador', state: 'Bahia', stateAbbr: 'BA', population: 2418005, region: 'Nordeste', economy: ['turismo', 'petroquímica', 'comércio', 'serviços'], context: 'Maior cidade do Nordeste por alguns rankings e capital cultural do Brasil, Salvador é um polo regional de serviços e turismo com crescente presença da economia digital.' },
  { slug: 'fortaleza', name: 'Fortaleza', state: 'Ceará', stateAbbr: 'CE', population: 2428678, region: 'Nordeste', economy: ['turismo', 'serviços', 'têxtil', 'tecnologia'], context: 'Fortaleza é o maior polo econômico do Ceará e um dos principais centros de turismo e negócios do Norte/Nordeste, com ecossistema crescente de startups e serviços digitais.' },
  { slug: 'belo-horizonte', name: 'Belo Horizonte', state: 'Minas Gerais', stateAbbr: 'MG', population: 2315560, region: 'Sudeste', economy: ['mineração', 'indústria', 'serviços', 'tecnologia'], context: 'Capital de Minas Gerais e maior cidade do interior brasileiro, Belo Horizonte é um hub regional de negócios com setor de serviços dinâmico e crescente polo de tecnologia.' },
  { slug: 'manaus', name: 'Manaus', state: 'Amazonas', stateAbbr: 'AM', population: 2063689, region: 'Norte', economy: ['indústria tecnológica', 'comércio', 'serviços', 'turismo'], context: 'A Zona Franca de Manaus atrai indústrias de eletrônicos e eletrodomésticos de todo o mundo, tornando a cidade o principal polo industrial da região Norte do Brasil.' },
  { slug: 'curitiba', name: 'Curitiba', state: 'Paraná', stateAbbr: 'PR', population: 1773733, region: 'Sul', economy: ['indústria automotiva', 'tecnologia', 'serviços', 'comércio'], context: 'Referência nacional em planejamento urbano e qualidade de vida, Curitiba possui um setor industrial diversificado liderado pelo segmento automotivo e um crescente polo de tecnologia.' },
  { slug: 'recife', name: 'Recife', state: 'Pernambuco', stateAbbr: 'PE', population: 1488920, region: 'Nordeste', economy: ['tecnologia', 'serviços', 'comércio', 'saúde'], context: 'O Porto Digital de Recife é um dos maiores parques tecnológicos do Brasil, posicionando a cidade como um dos principais centros de inovação digital do Nordeste.' },
  { slug: 'goiania', name: 'Goiânia', state: 'Goiás', stateAbbr: 'GO', population: 1412364, region: 'Centro-Oeste', economy: ['agronegócio', 'saúde', 'comércio', 'serviços'], context: 'Maior polo de saúde do Centro-Oeste e hub de serviços para o agronegócio regional, Goiânia tem um mercado consumidor aquecido e em constante expansão.' },
  { slug: 'porto-alegre', name: 'Porto Alegre', state: 'Rio Grande do Sul', stateAbbr: 'RS', population: 1332570, region: 'Sul', economy: ['indústria', 'agronegócio', 'tecnologia', 'serviços'], context: 'Capital do estado mais ao sul do Brasil, Porto Alegre é um centro financeiro e comercial importante com tradição industrial e crescente ecossistema de tecnologia e inovação.' },
  { slug: 'belem', name: 'Belém', state: 'Pará', stateAbbr: 'PA', population: 1303403, region: 'Norte', economy: ['comércio', 'serviços', 'agropecuária', 'turismo'], context: 'Porta de entrada para a Amazônia, Belém é o principal centro comercial e de serviços da região Norte, com uma economia em expansão impulsionada pelo agronegócio e pelo turismo.' },
  { slug: 'guarulhos', name: 'Guarulhos', state: 'São Paulo', stateAbbr: 'SP', population: 1291369, region: 'Sudeste', economy: ['logística', 'indústria', 'comércio', 'serviços'], context: 'Sede do maior aeroporto da América do Sul, Guarulhos é um dos maiores polos industriais e logísticos do estado de São Paulo, com intensa atividade comercial e de serviços.' },
  { slug: 'campinas', name: 'Campinas', state: 'São Paulo', stateAbbr: 'SP', population: 1139047, region: 'Sudeste', economy: ['tecnologia', 'agronegócio', 'indústria', 'serviços'], context: 'Lar da Unicamp e de centros de pesquisa de multinacionais, Campinas é reconhecida como a capital da tecnologia do interior paulista, com um ecossistema de inovação robusto.' },
  { slug: 'sao-luis', name: 'São Luís', state: 'Maranhão', stateAbbr: 'MA', population: 1037775, region: 'Nordeste', economy: ['porto', 'indústria', 'serviços', 'comércio'], context: 'Com o maior porto exportador de minério de ferro do mundo, São Luís é o principal centro logístico e industrial do Maranhão e uma das economias de maior crescimento do Norte/Nordeste.' },
  { slug: 'maceio', name: 'Maceió', state: 'Alagoas', stateAbbr: 'AL', population: 932748, region: 'Nordeste', economy: ['turismo', 'serviços', 'indústria química', 'comércio'], context: 'Capital do estado de Alagoas, Maceió é um destino turístico consolidado com praias de fama internacional e um setor de serviços que cresce junto com o fluxo de visitantes.' },
  { slug: 'natal', name: 'Natal', state: 'Rio Grande do Norte', stateAbbr: 'RN', population: 803739, region: 'Nordeste', economy: ['turismo', 'serviços', 'carcinicultura', 'comércio'], context: 'Capital do estado do Rio Grande do Norte, Natal é reconhecida internacionalmente pelo turismo de sol e mar e tem uma economia local movida por serviços e comércio.' },
  { slug: 'teresina', name: 'Teresina', state: 'Piauí', stateAbbr: 'PI', population: 840600, region: 'Nordeste', economy: ['comércio', 'serviços', 'saúde', 'administração pública'], context: 'Principal polo de saúde do Piauí e Maranhão, Teresina atrai pacientes e investimentos em saúde de toda a região, com um comércio varejista forte e crescente setor de serviços.' },
  { slug: 'campo-grande', name: 'Campo Grande', state: 'Mato Grosso do Sul', stateAbbr: 'MS', population: 898073, region: 'Centro-Oeste', economy: ['agronegócio', 'comércio', 'serviços', 'indústria'], context: 'Capital do Mato Grosso do Sul e porta de entrada para o Pantanal, Campo Grande é o hub regional do agronegócio local — estado que lidera a produção de carne bovina no Brasil.' },
  { slug: 'joao-pessoa', name: 'João Pessoa', state: 'Paraíba', stateAbbr: 'PB', population: 779025, region: 'Nordeste', economy: ['turismo', 'serviços', 'comércio', 'tecnologia'], context: 'A segunda cidade mais a leste das Américas, João Pessoa combina um litoral exuberante com uma economia de serviços diversificada e uma administração pública significativa.' },
  { slug: 'osasco', name: 'Osasco', state: 'São Paulo', stateAbbr: 'SP', population: 696850, region: 'Sudeste', economy: ['serviços financeiros', 'comércio', 'indústria', 'serviços'], context: 'Um dos maiores polos financeiros do Brasil fora de São Paulo, Osasco concentra sedes de grandes bancos e financeiras, além de intensa atividade comercial e industrial.' },
  { slug: 'sao-bernardo-do-campo', name: 'São Bernardo do Campo', state: 'São Paulo', stateAbbr: 'SP', population: 833240, region: 'Sudeste', economy: ['indústria automotiva', 'serviços', 'comércio', 'tecnologia'], context: 'Coração industrial do ABC paulista, São Bernardo do Campo é sede de montadoras e fabricantes de autopeças de renome mundial, além de um setor de serviços em forte crescimento.' },
  { slug: 'santo-andre', name: 'Santo André', state: 'São Paulo', stateAbbr: 'SP', population: 718636, region: 'Sudeste', economy: ['indústria', 'comércio', 'serviços', 'tecnologia'], context: 'Parte do Grande ABC paulista, Santo André tem uma economia diversificada com forte presença industrial e um comércio varejista expressivo que atende a região metropolitana.' },
  { slug: 'jaboatao-dos-guararapes', name: 'Jaboatão dos Guararapes', state: 'Pernambuco', stateAbbr: 'PE', population: 694942, region: 'Nordeste', economy: ['indústria', 'comércio', 'serviços', 'logística'], context: 'Segunda maior cidade de Pernambuco, Jaboatão dos Guararapes abriga importantes polos industriais e centros comerciais que atendem a Região Metropolitana do Recife.' },
  { slug: 'sao-jose-dos-campos', name: 'São José dos Campos', state: 'São Paulo', stateAbbr: 'SP', population: 699767, region: 'Sudeste', economy: ['aeroespacial', 'tecnologia', 'indústria', 'serviços'], context: 'Sede da Embraer e de institutos de pesquisa como o INPE e o ITA, São José dos Campos é o principal polo aeroespacial e tecnológico do Brasil, com alto nível de inovação.' },
  { slug: 'uberlandia', name: 'Uberlândia', state: 'Minas Gerais', stateAbbr: 'MG', population: 699097, region: 'Sudeste', economy: ['logística', 'agronegócio', 'comércio', 'serviços'], context: 'Posicionada no coração do Brasil, Uberlândia é um dos maiores centros de distribuição logística do país, servindo como hub de comércio e serviços para toda a região do Triângulo Mineiro.' },
  { slug: 'contagem', name: 'Contagem', state: 'Minas Gerais', stateAbbr: 'MG', population: 663758, region: 'Sudeste', economy: ['indústria', 'logística', 'comércio', 'serviços'], context: 'Município da Grande BH com um dos maiores parques industriais de Minas Gerais, Contagem abriga fabricantes de alimentos, metais e produtos farmacêuticos de expressão nacional.' },
  { slug: 'sorocaba', name: 'Sorocaba', state: 'São Paulo', stateAbbr: 'SP', population: 686392, region: 'Sudeste', economy: ['indústria', 'educação', 'comércio', 'serviços'], context: 'Importante polo industrial do interior paulista, Sorocaba se destaca na produção têxtil, metalúrgica e tecnológica, além de contar com um setor educacional robusto.' },
  { slug: 'aracaju', name: 'Aracaju', state: 'Sergipe', stateAbbr: 'SE', population: 665100, region: 'Nordeste', economy: ['petróleo', 'turismo', 'comércio', 'serviços'], context: 'Capital sergipana e uma das menores capitais do Brasil, Aracaju tem na exploração de petróleo offshore e no turismo seus principais motores econômicos, com comércio aquecido.' },
  { slug: 'feira-de-santana', name: 'Feira de Santana', state: 'Bahia', stateAbbr: 'BA', population: 615900, region: 'Nordeste', economy: ['comércio', 'indústria', 'serviços', 'logística'], context: 'Maior município do interior da Bahia e principal entroncamento rodoviário do Nordeste, Feira de Santana é um polo comercial e industrial que serve toda a região.' },
  { slug: 'cuiaba', name: 'Cuiabá', state: 'Mato Grosso', stateAbbr: 'MT', population: 624000, region: 'Centro-Oeste', economy: ['agronegócio', 'comércio', 'serviços', 'construção civil'], context: 'Capital do estado que lidera a produção de soja, algodão e boiada no Brasil, Cuiabá é o hub de serviços e comércio para um dos maiores estados produtores do agronegócio mundial.' },
  { slug: 'joinville', name: 'Joinville', state: 'Santa Catarina', stateAbbr: 'SC', population: 593071, region: 'Sul', economy: ['metalurgia', 'eletrônica', 'plásticos', 'serviços'], context: 'Maior cidade de Santa Catarina e um dos maiores polos industriais do Sul do Brasil, Joinville se destaca na produção de peças metálicas, motores elétricos e componentes para a indústria.' },
  { slug: 'aparecida-de-goiania', name: 'Aparecida de Goiânia', state: 'Goiás', stateAbbr: 'GO', population: 581946, region: 'Centro-Oeste', economy: ['comércio', 'indústria', 'serviços', 'logística'], context: 'Segunda maior cidade de Goiás, Aparecida de Goiânia é um importante polo industrial e de serviços na região metropolitana de Goiânia, com crescimento econômico acelerado.' },
  { slug: 'londrina', name: 'Londrina', state: 'Paraná', stateAbbr: 'PR', population: 553393, region: 'Sul', economy: ['agronegócio', 'comércio', 'saúde', 'educação'], context: 'Chamada de capital do Norte do Paraná, Londrina é um polo regional de saúde, educação e serviços, além de um dos maiores centros de comercialização de grãos do estado.' },
  { slug: 'ananindeua', name: 'Ananindeua', state: 'Pará', stateAbbr: 'PA', population: 535236, region: 'Norte', economy: ['indústria', 'comércio', 'serviços', 'logística'], context: 'Parte da Região Metropolitana de Belém, Ananindeua abriga parques industriais e centros comerciais que atendem a capital paraense e toda a região norte do estado.' },
  { slug: 'niteroi', name: 'Niterói', state: 'Rio de Janeiro', stateAbbr: 'RJ', population: 515012, region: 'Sudeste', economy: ['petróleo', 'construção naval', 'serviços', 'comércio'], context: 'Centro de operações da indústria de petróleo e gás offshore e da construção naval, Niterói tem um alto IDH e um setor de serviços sofisticado na margem da Baía de Guanabara.' },
  { slug: 'serra', name: 'Serra', state: 'Espírito Santo', stateAbbr: 'ES', population: 527230, region: 'Sudeste', economy: ['indústria siderúrgica', 'petroquímica', 'logística', 'serviços'], context: 'Maior polo industrial do Espírito Santo, Serra abriga plantas siderúrgicas e petroquímicas de grande porte, além de um movimentado porto que impulsiona a economia regional.' },
  { slug: 'duque-de-caxias', name: 'Duque de Caxias', state: 'Rio de Janeiro', stateAbbr: 'RJ', population: 919595, region: 'Sudeste', economy: ['petroquímica', 'logística', 'comércio', 'serviços'], context: 'Uma das maiores economias do Rio de Janeiro, Duque de Caxias abriga a maior refinaria de petróleo do Brasil (Reduc) e é um polo logístico estratégico da Região Metropolitana carioca.' },
  { slug: 'sao-jose-do-rio-preto', name: 'São José do Rio Preto', state: 'São Paulo', stateAbbr: 'SP', population: 466741, region: 'Sudeste', economy: ['agronegócio', 'saúde', 'comércio', 'serviços'], context: 'Principal polo de saúde e comércio do Noroeste Paulista, São José do Rio Preto atende uma vasta região produtora de cana-de-açúcar, citricultura e gado de corte.' },
  { slug: 'belford-roxo', name: 'Belford Roxo', state: 'Rio de Janeiro', stateAbbr: 'RJ', population: 495698, region: 'Sudeste', economy: ['comércio', 'indústria', 'serviços', 'logística'], context: 'Integrante da Região Metropolitana do Rio de Janeiro, Belford Roxo tem uma economia voltada para o comércio local e a indústria, servindo uma população de quase 500 mil habitantes.' },
  { slug: 'nova-iguacu', name: 'Nova Iguaçu', state: 'Rio de Janeiro', stateAbbr: 'RJ', population: 819186, region: 'Sudeste', economy: ['comércio', 'serviços', 'indústria', 'logística'], context: 'Um dos municípios mais populosos do estado do Rio de Janeiro, Nova Iguaçu é um polo comercial e de serviços da Baixada Fluminense, com ampla rede de estabelecimentos locais.' },
  { slug: 'ribeirao-preto', name: 'Ribeirão Preto', state: 'São Paulo', stateAbbr: 'SP', population: 711825, region: 'Sudeste', economy: ['agronegócio', 'saúde', 'biotecnologia', 'serviços'], context: 'Conhecida como a "capital do agronegócio", Ribeirão Preto é também um polo nacional de saúde e biotecnologia, com hospitais e clínicas que atendem toda a região de Ribeirão.' },
  { slug: 'florianopolis', name: 'Florianópolis', state: 'Santa Catarina', stateAbbr: 'SC', population: 508826, region: 'Sul', economy: ['tecnologia', 'turismo', 'serviços', 'administração pública'], context: 'A "Ilha da Magia" é um dos maiores polos de startups e tecnologia do Brasil, com centenas de empresas de software e um turismo de alto nível que movimenta a economia o ano todo.' },
  { slug: 'mogi-das-cruzes', name: 'Mogi das Cruzes', state: 'São Paulo', stateAbbr: 'SP', population: 453662, region: 'Sudeste', economy: ['horticultura', 'indústria', 'logística', 'serviços'], context: 'Maior produtor de hortaliças, cogumelos e flores do Brasil, Mogi das Cruzes é também um polo de indústrias diversas e serve como nó logístico entre a capital paulista e o Vale do Ribeira.' },
  { slug: 'santos', name: 'Santos', state: 'São Paulo', stateAbbr: 'SP', population: 428923, region: 'Sudeste', economy: ['porto', 'logística', 'turismo', 'serviços'], context: 'Sede do maior porto da América Latina, Santos é um dos centros de comércio exterior mais importantes do hemisfério Sul, além de um destino turístico histórico no litoral paulista.' },
  { slug: 'betim', name: 'Betim', state: 'Minas Gerais', stateAbbr: 'MG', population: 444515, region: 'Sudeste', economy: ['indústria automotiva', 'petroquímica', 'serviços', 'comércio'], context: 'Lar da maior fábrica da Fiat fora da Itália, Betim é um dos principais polos industriais de Minas Gerais, combinando a produção automotiva com um complexo petroquímico expressivo.' },
  { slug: 'macapa', name: 'Macapá', state: 'Amapá', stateAbbr: 'AP', population: 512902, region: 'Norte', economy: ['comércio', 'serviços', 'mineração', 'pesca'], context: 'Única capital estadual cortada pela linha do Equador, Macapá é o centro econômico do Amapá, com comércio aquecido por conta de incentivos fiscais e da fronteira com a Guiana Francesa.' },
  { slug: 'porto-velho', name: 'Porto Velho', state: 'Rondônia', stateAbbr: 'RO', population: 539353, region: 'Norte', economy: ['agropecuária', 'energia elétrica', 'serviços', 'comércio'], context: 'Capital de Rondônia e sede das usinas hidrelétricas do Madeira, Porto Velho tem sua economia dinamizada pelo agronegócio crescente do estado e pelo setor de energia elétrica.' },
  { slug: 'maua', name: 'Mauá', state: 'São Paulo', stateAbbr: 'SP', population: 462919, region: 'Sudeste', economy: ['indústria química', 'plásticos', 'comércio', 'serviços'], context: 'Parte do Grande ABC Paulista, Mauá é um importante polo industrial especializado em química, plásticos e metalurgia, integrando a maior região industrial do Brasil.' },
  { slug: 'caxias-do-sul', name: 'Caxias do Sul', state: 'Rio Grande do Sul', stateAbbr: 'RS', population: 457132, region: 'Sul', economy: ['metalurgia', 'vinicultura', 'indústria', 'serviços'], context: 'A capital nacional da uva e do vinho e um dos maiores polos metalúrgicos do Sul do Brasil, Caxias do Sul tem uma base industrial diversificada com forte tradição em exportações.' },
  { slug: 'carapicuiba', name: 'Carapicuíba', state: 'São Paulo', stateAbbr: 'SP', population: 428000, region: 'Sudeste', economy: ['comércio', 'serviços', 'indústria', 'logística'], context: 'Município da Grande São Paulo com perfil residencial e comercial, Carapicuíba tem uma economia de serviços voltada para a vasta população local e para a integração com a metrópole paulistana.' },
  { slug: 'diadema', name: 'Diadema', state: 'São Paulo', stateAbbr: 'SP', population: 426319, region: 'Sudeste', economy: ['farmacêutica', 'química', 'plásticos', 'comércio'], context: 'Um dos maiores polos farmacêuticos e de cosméticos do Brasil, Diadema concentra dezenas de fabricantes do setor e tem alta densidade industrial por km², integrando o ABC Paulista.' },
]

export function getCityBySlug(slug: string): CityData | undefined {
  return cities.find((c) => c.slug === slug)
}

export function getCitiesByRegion(region: string, excludeSlug: string, limit = 8): CityData[] {
  return cities.filter((c) => c.region === region && c.slug !== excludeSlug).slice(0, limit)
}
